### ISSUE TITLE
__init__() missing 4 required positional arguments: 'z_dim', 'style_dim', 'f_dim', and 'hidden_dim'

### ISSUE THREAD

**Issue by shichen-wang** [silence-tang/ArtNeRF#2]
when i run python train_artnerf.py --curriculum=face2anime，meet this error，how can i fix it？

python train_artnerf.py --curriculum=face2anime
Namespace(curriculum='face2anime', fid_interval=2000, load_dir='', model_save_interval=6000, n_epochs=1000, output_dir='out_dir', port='16666', sample_interval=2000, set_step=None)
Traceback (most recent call last):
  File "train_artnerf.py", line 579, in <module>
    train(opt)
  File "train_artnerf.py", line 122, in train
    generator = getattr(generators_artnerf, metadata['generator'])(FiLM, metadata['z_dim'], metadata['hidden_dim']).to(device)
TypeError: __init__() missing 4 required positional arguments: 'z_dim', 'style_dim', 'f_dim', and 'hidden_dim'

**Comment by silence-tang** [comment]
Hi, I just updated the readme and the whole project, I also released the pretrained models. Please clone the project and follow the readme to setup.
